#!/usr/bin/env php
<?php

namespace think;

// 加载基础文件
require __DIR__ . '/thinkphp/base.php';

define('APP_PATH', __DIR__ . '/application/');
define('WEB_ROOT', __DIR__ . '/public/');
define('ROOT_PATH', __DIR__ . '/');

// 应用初始化
Container::get('app')->path(__DIR__ . '/application/')->initialize();

// 控制台初始化
Console::init();